---
title: Projektbericht Ausleihbar
subtitle: Software- und Plattformarchitektur
date: 08.03.2025
author:
  - Andreas Burri
  - Dominic Rohner
  - Giuseppe Zaino
  - Luca Zaugg
  - Marcel Borter
  - Séverin Kiener
footer-left: A. Burri, D. Rohner, G. Zaino, L. Zaugg, M. Borter, S. Kiener
language: de-CH
dozent: Fabian Hirter
abgabetermin: 09.03.2025
---

