---
title: Projektbericht Wissensmanagement
subtitle: Lösungsalgorithmen
date: 13.03.2025
author:
  - Dominic Rohner
  - Marcel Borter
language: de-CH
dozent: Christian Herren
abgabetermin: 17.03.2025
---

